FROM node:lts-alpine

RUN npm i -g http-server
ENTRYPOINT ["http-server"]

LABEL org.opencontainers.image.title="http-server" \
  org.opencontainers.image.authors="mebtte<hi@mebtte.com>" \
  org.opencontainers.image.url="https://github.com/mebtte/docker"
