name: frp

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  frp:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-node@main
      - uses: actions/checkout@main

      - run: ./frp/build_and_push.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mebtte/frps
          short-description: "A docker image for frps."
          readme-filepath: "./frp/readme.md"

      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mebtte/frpc
          short-description: "A docker image for frpc."
          readme-filepath: "./frp/readme.md"
