name: build from latest frpc and push

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-node@main
      - uses: actions/checkout@main

      - run: ./frp/build_and_push.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
