name: build from latest frpc and push

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@main

      - run: |
          docker pull mebtte/cicada:beta
          docker run -it --rm mebtte/cicada:beta cicada --version
